drop table "T_PRODUCT_CATEGORY";
drop table "T_PRODUCT";
drop table "T_CATEGORY";

CREATE TABLE "T_CATEGORY" (
    "CATEGORY_ID" INT PRIMARY KEY,
    "NAME"        VARCHAR2(64)  NOT NULL,
    "LVL"         INT NOT NULL,
    "PARENT"      INT DEFAULT NULL,
    "PATH"        VARCHAR2(256) NOT NULL,
    "LEFT"        NUMBER(19, 0) NOT NULL,
    "RIGHT"       NUMBER(19, 0) NOT NULL,
    CONSTRAINT "T_CATEGORY_PARENT" FOREIGN KEY ("PARENT")
        REFERENCES "T_CATEGORY"("CATEGORY_ID")
);

create index "IX_CATEGORY_BOUNDS"
    on "T_CATEGORY" ("LEFT", "RIGHT");

create index "IX_CATEGORY_PARENT"
    on "T_CATEGORY" ("PARENT");

CREATE TABLE "T_PRODUCT" (
    "PRODUCT_ID" INT PRIMARY KEY,
    "NAME"       VARCHAR2(64)  NOT NULL,
    "PRICE"      DECIMAL(15, 3) NOT NULL,
    "LEFT"       NUMBER(19, 0) NOT NULL,
    "RIGHT"      NUMBER(19, 0) NOT NULL
);

create index "IX_PRODUCT_BOUNDS"
    on "T_PRODUCT" ("LEFT", "RIGHT");

CREATE TABLE "T_PRODUCT_CATEGORY" (
    "CATEGORY_ID" INT NOT NULL,
    "PRODUCT_ID"  INT NOT NULL,
    CONSTRAINT "T_CAT_PROD_CAT_ID_FK" FOREIGN KEY ("CATEGORY_ID")
        REFERENCES "T_CATEGORY"("CATEGORY_ID") ON DELETE CASCADE,
    CONSTRAINT "T_PROD_CAT_PROD_ID_FK" FOREIGN KEY ("CATEGORY_ID")
        REFERENCES "T_PRODUCT"("PRODUCT_ID") ON DELETE CASCADE
);

create index "IX_PRODUCT_CATEGORY_CAT"
    on "T_PRODUCT_CATEGORY" ("CATEGORY_ID");

create index "IX_PRODUCT_CATEGORY_PRO"
    on "T_PRODUCT_CATEGORY" ("PRODUCT_ID");